#!/bin/bash

set -o errexit
set -o nounset

NO_LOGS=0

usage() {
    echo "Usage: $0 [OPTIONS]"
    echo
    echo "Options:"
    echo "  -n, --no-logs   Disable logging"
    echo "  -h, --help      Show this help message"
}

# Iterate over all arguments
for arg in "$@"; do
    case "$arg" in
        --no-logs|-n)
            NO_LOGS=1
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            usage
            exit 0
            ;;
    esac
done

if [ "$NO_LOGS" -eq 1 ];
then
    echo "===> Logging disabled..."
else
    echo "===> Logging enabled..."
fi

# Generate .env if it doesn't exist so that the notebooks
# can be authenticated via a unique token.
ENV_FILE=".env"
if [[ ! -f "$ENV_FILE" ]];
then
    echo "===> Generating new .env..."
    echo "JUPYTER_TOKEN=$(openssl rand -hex 32 </dev/urandom)" > "$ENV_FILE"
fi
TOKEN=$(grep JUPYTER_TOKEN .env | cut -d= -f2)
echo "===> Using token: $TOKEN"

# The Docker container can only write into this
# host directory and the config directory.
mkdir -p notebooks

echo "===> Taking down any running notebooks..."
docker compose down

echo "===> Buidling and starting Jupyter Docker..."
COMPOSE_BAKE=true docker-compose up --build -d

# Setup a Python virtual env on the host side.
VENV_PATH="$HOME/.venvs/ai-agents"
if [[ ! -d "$VENV_PATH" ]];
then
    echo "===> Creating virtual environment..."
    python3 -m venv "$VENV_PATH"
fi
source "$VENV_PATH/bin/activate"

echo "===> Installing host dependencies..."
pip install --upgrade pip >/dev/null
pip install jupyterlab nbformat >/dev/null

echo "===> Notebook available at:"
echo "  http://localhost:8888/lab?token=$TOKEN"
echo "===> Remember to run this command in a notebook cell:"
echo "  %load_ext jupyter_ai_magics"

# Cleanup secret value.
unset TOKEN

if [ "$NO_LOGS" -eq 0 ];
then
    echo "===> Tailing logs..."
    docker logs --follow ai-jupyter
fi
